packages:
  - apps/*
  - tooling/*

catalog:
  eslint: ^9.39.1
  prettier: ^3.7.4
  typescript: ^5.9.3

catalogs:
  react:
    react: 19.2.1
    react-dom: 19.2.1
    '@types/react': 19.2.7
    '@types/react-dom': 19.2.3

onlyBuiltDependencies:
  - sharp
