packages:
  - apps/*
  - tooling/*

catalog:
  eslint: ^9.39.1
  prettier: ^3.6.2
  typescript: ^5.9.3

catalogs:
  react:
    react: 19.2.0
    react-dom: 19.2.0
    '@types/react': 19.2.2
    '@types/react-dom': 19.2.2

onlyBuiltDependencies:
  - sharp
