packages:
  - apps/*
  - tooling/*

catalog:
  eslint: ^9.18.0
  prettier: ^3.4.2
  typescript: ^5.7.3

catalogs:
  react:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': 19.0.7
    '@types/react-dom': 19.0.3
