packages:
  - apps/*
  - tooling/*

catalog:
  eslint: ^9.12.0
  prettier: ^3.3.3
  typescript: ^5.6.3

catalogs:
  react:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': 19.0.4
    '@types/react-dom': 19.0.2
