name: "📄  "

inputs:
  export-directory:
    required: true

runs:
  using: "composite"
  steps:
    - name: "💽️  Setup"
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.0.x"

    - name: "📄️  Export"
      shell: bash
      run: dotnet run --project ./src/Service.Supervisor/src/HttpApi -- schema export --output ${{ inputs.export-directory }}/schema.graphql

    - name: "⚡️  Build"
      shell: bash
      working-directory: ${{ inputs.export-directory }}
      run: pnpm build:relay
